### ISSUE TITLE
As a STEM program manager, I want to scale my program so I can raise the outreach and impact to my community, keeping in mind that my audience may have limited resources to engage with my program. 

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#1]
**Tasks**

- [x] Help team understand available resources such as team members and project scope
- [x] Attend demo day (4/30) and final partner meeting (5/7)
- [x] Provide weekly update to team as priorities are quickly changing and evolving for remote educational initiatives 

**Acceptance Criteria** 

- [x] Ongoing understanding of Tim’s current platform and ongoing projects
