### ISSUE TITLE
As a student, I want more access to technology so that I can learn more about climate change/STEM fields.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#11]
**Tasks**

- [ ] Access events schedule
- [ ] Reminder to attend sessions
- [ ] Share events with friends

**Acceptance Criteria**

- [ ] Attendance at event
- [ ] Consistent engagement in sessions
- [ ] Asking questions in sessions
