### ISSUE TITLE
As a policymaker, I want comparable data so that I can tweak policies to serve their intended purpose and demographic.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#12]
**Tasks**

- [ ] Familiarize self with current educational framework for climate resiliency/STEM
- [ ] Consult industry experts from education and industry about programming
- [ ] Canvas users/stakeholders about their wants, needs, and feelings
- [ ] Conduct benchmarking

**Acceptance Criteria**

- [ ] User interviews
- [ ] Expert interviews
- [ ] Workforce data analysis and trends
