### ISSUE TITLE
Sprint Three

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#13]
**Tasks**

- [x] review assignment
- [x] share agendas with team and partners
- [x] confirm user contacts with partners
- [x] identify team tasks
- [x] provide weekly update to partners
- [x] reach out to user contacts to schedule interviews

**Acceptance Criteria**

- [x] assignment completed and submitted
