### ISSUE TITLE
Sprint Two

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#15]
**Task**

- [x] Additional research on PA Rural Robotics/Communitopia
- [x] Revisit list of stakeholders
- [x] Create personas
- [x] Map user journeys
- [x] Create a meeting agenda that includes:
-Proposed areas of focus to discuss with stakeholders
-List of prepared questions 
- [x] Asking stakeholders how to engage with their respective end users
- [x] Understand in-depth what type(s) of technology stakeholders are currently using (hardware/software) and where they see opportunities and limitations
- [x] Ask if they are taking advantage of any existing policies to enable achievement of their goals
- [x] Ask if any existing policies are hindering their ability to achieve their goal(s)
- [ ] Find relevant case studies, understanding what tools/methods similar organizations used to successfully achieve their goals can help us brainstorm ideas
- [ ] Become aware of government/high level priorities and timelines; i.e. how much money has the government put into the development of STEM careers and how are those funds being channeled into the public domain right now. Who is it reaching and missing?
- [x] Share weekly progress with partners
