### ISSUE TITLE
As a community partner, I want to combine efforts with/lend assistance to other organizations so that I can achieve a bigger impact.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#16]
**Tasks**

- [X] Research and find suitable organizations 
- [X] Budget planning 
- [X] Resource planning
- [X] Review and monitor progress 

**Acceptance Criteria**

- [X] Finance and progress reporting (data)
- [X] End-user feedback
- [X] Milestone achievements
