### ISSUE TITLE
Sprint Four

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#17]
**Tasks**

- [x] Review Assignment

- [x] Share agendas with team and partners

- [x] Confirm status/conduct user interviews

- [x] Identify team tasks

- [x] Begin wireframing and prototyping
