### ISSUE TITLE
UX-Industry Expert

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#18]
**Tasks**

- [x] Conduct interview with industry expert

**Acceptance Criteria**

- [x] Send interview request and confirm time
- [x] Update interview script and questions
- [x] Send thank you email
- [x] Transcribe notes
- [X] Apply UX to prototype
