### ISSUE TITLE
UX Interviews - HS Administrator

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#19]
**Tasks**

- [x] Conduct interview with high school administrator

**Acceptance Criteria**

- [x] Send interview request and confirm time
- [x] Update interview script and questions
- [x] Send thank you email
- [x] Transcribe notes
- [X] Apply UX to prototype
