### ISSUE TITLE
As the Communitopia program director, I want to increase engagement with my program and develop a technological hub so that I can grow Communitopia in a manageable way. 

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#2]
**Tasks**

- [x] Attend demo day (4/30) and final partner meeting (5/7)
- [x] Provide weekly update to team as priorities are quickly changing and evolving for remote educational initiatives
- [x] Help team understand available resources such as team members and project scope

**Acceptance Criteria**

- [x] Ongoing understanding of Katie’s projects, initiatives, and organizational priorities
