### ISSUE TITLE
UX-Teacher/STEM coach

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#20]
**Tasks**

- [x] Conduct interview with teacher/STEM coach

**Acceptance Criteria**

- [x] Send interview request and confirm time
- [x] Update interview script and questions
- [x] Send thank you email
- [x] Transcribe notes 
- [x] Apply UX to prototype
