### ISSUE TITLE
UX-Community Partner

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#21]
**Tasks**

- [X] Conduct interview with community partner

**Acceptance Criteria**

- [x] Send interview request and confirm time
- [X] Update interview script and questions
- [X] Send thank you email
- [X] Transcribe notes
- [X] Apply UX to prototype
