### ISSUE TITLE
Sprint Five

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#22]
**Tasks**

- [X] Conduct final user interview
- [X] Synthesize user research
- [X] Finalize MVP demo day presentation
- [X] Finalize MVP deliverable/documentation
- [X] Submit all Sprint Five collateral

**Acceptance Criteria**

- [X] Finalize MVP prototype for class demo day (April 30)
- [X] Conduct final project handoff with partners (May 7)
- [X] Submit all MVP project collateral to Canvas (May 8)
