### ISSUE TITLE
As an Industry Expert, I want to have an awareness of the organizations in my community that align with my company’s mission and vision so that I can work collaboratively to identify opportunities.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#23]
**Tasks**

- [X] Consult with area colleges/universities that may be already partnered with these organizations
- [X] Consult with industry collaborative networks that may already be familiar with such organizations
- [X] Give staff the opportunity to share their knowledge of community engagement opportunities

**Acceptance criteria**

- [X] Build relationships with these organizations
- [X] Identify possible pipeline strategy for recruiting and retaining talent in the region
- [X] Be open to opportunities to partner and collaborate with others
