### ISSUE TITLE
As a High School Administrator, I want to ensure that I am continuously working to bring innovative and agile practices to my educational approach so that I can best serve the students, teachers, parents, and greater community within the school district that I work.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#24]
**Tasks**

- [x] Benchmarking other districts that are similar in demographic and achievement
- [x] Developing relationships with potential funders (e.g foundations, school board members, and community business leaders)
- [x] Staying current/knowledgeable about curriculum updates/advancements within the state
- [x] Work to inspire innovation with teachers in/out of the classroom

**Acceptance criteria**

- [x] Look at what others are doing around you
- [x] Connect with the greater community through activities, events, and potential partnerships
- [x] Attend state-wide educational conferences and building relationships with colleagues
- [x] Establish feedback loop with teachers to encourage creative solutions
