### ISSUE TITLE
As a teacher and STEM coach, I want to provide enhanced learning opportunities for my students so that I can introduce them to STEM principles in a way that excites knowledge and teamwork. 

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#25]
**Tasks**

- [X] Foster opportunities for experiential learning via workshops and extracurricular activities 
- [X] Encourage collaboration and problem solving among/across teams
- [X] Build relationships/network with other coaches/STEM educators to share resources, opportunities, and ideas for growth.

**Acceptance Criteria**

- [X] Designing curriculum
- [X] Hosting activities
- [X] Engaging students, parents, coaches, and others to be a part of the process
