### ISSUE TITLE
As a User Researcher, I want to thoroughly understand user insights so that I can gain a view of the current platform and its opportunities for development. 

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#3]
**Tasks**

- [x] Work on project timeline 
- [x] Unpack “opportunities” and the expectations for final deliverable
- [x] Perform user interviews to better understand the problem space

**Acceptance Criteria**

- [x] List users open to being interviewed
- [x] Initial list of interview questions, to be reviewed with the team
