### ISSUE TITLE
As the implementation & technology specialist, I want to fully understand the steps needed to complete each sponsor’s goal so I can find the best resources to utilize. 

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#4]
**Tasks**

- [x] Research and assess existing technologies being utilized
- [x] Research potential new technology for first prototype
- [x] Work on project timeline 
- [x] Unpack “opportunities” and the expectations for final deliverable
- [x] Get sense of current technology in place
- [x] Understand what technologies sponsors might be interested in
- [x] Scope out opportunities based on top 3 “improvements” suggested by sponsors

**Acceptance Criteria**

- [x] Plan for approaching first prototype
- [x] Scope out opportunities based top 3 "improvements" suggested by sponsors
- [x] List technology being used now
- [x] Develop questions for user research that lead to insight on how things get implemented in the Communitopia/Robotics programs
