### ISSUE TITLE
As a policy specialist, I want a full grasp on the context and working of the organisations that are being researched, in order to best identify opportunities, threats & problems and to form policies that can better the organisations.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#5]
**Tasks**

- [ ] Do literature research to find case studies, similar organisations, and (implemented) policies
- [ ] Try to find how other programs are handing this time of crisis
- [ ] Find opportunities, threats & problems

**Acceptance Criteria**
- [ ] List of ideas to improve outreach in this time of crisis
- [ ] List of case studies
- [ ] List of opportunities, threads & problems
- [ ] Literature research of case studies, similar organisations and policies
