### ISSUE TITLE
As a project manager, I want to have a full understanding of the project’s components so that I can effectively define it’s scope to manage tasks and timeline

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#6]
**Tasks**

- [X] Refinement of project scope, goals, timeline, and deliverables 
- [X] Ongoing communication with Katie, Tim, and Heinz team
- [X] Update user research consent forms, interview questions, and script
- [X] Conduct user research interviews, log notes, and synthesize findings
- [X] Submit key performance indicators and risk analysis to MVP
- [X] Ongoing updates to Kanban board, project timeline, Miro board, and Sprint Five documentation
- [X] Move team toward MVP presentation on 4/30, final partner meeting on 5/7, and final project submission on 5/8

**Acceptance Criteria**

- [X] User research interviews scheduled, conducted, and analyzed
- [X] Finalize MVP prototype to share on demo day 4/30
- [X] Facilitate final partner meeting on 5/7
- [X] Share final project MVP with partners on 5/8
- [X] Share final project deliverables for class on Canvas on 5/8
