### ISSUE TITLE
As a parent, I want subsidized fees so that I can enroll my child/children in climate change/STEM programs.

### ISSUE THREAD

**Issue by jasciullo** [jasciullo/robotics_communitopia#9]
**Tasks**

- [ ] Get kids signed up and transported to event (if applicable)
- [ ] Get kids any necessary resources for attending the event

**Acceptance Criteria**

- [ ] Child's attendance and ability to perform necessary tasks
